[package]
name = "ai-shot-core"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
gemini-rust.workspace = true
screenshots.workspace = true
base64.workspace = true
eframe.workspace = true
dotenvy.workspace = true
url.workspace = true
image.workspace = true